### ISSUE TITLE
Compatibility with acfbentveld/xml

### ISSUE THREAD

**Issue by chiiya** [Flowgistics/laravel-xml#1]
This package is only compatible with PHP8+. It seems like you completely replaced `acfbentveld/xml` (which was previously compatible with PHP7.2+) with this new package, meaning that any project using `acfbentveld/xml` and < PHP8 is now broken. `acfbentveld/xml` does not exist anymore, so I can't even stay on the old version.

```
Failed to download acfbentveld/xml from dist: The "https://api.github.com/repos/ACFBentveld/XML/zipball/e13034795fb1b64a9be5f23dce46ff6673d5a75a" file could not be downloaded (HTTP/2 404 )
```

Please either restore the `acfbentveld/xml` repository and simply archive it, inserting a warning and link to this new repository, or provide a version of this package compatible with older PHP versions so that we can use it as a drop-in replacement.

**Comment by AmandoVledder** [comment]
Hi, the `acfbentveld/xml` repo has been restored & archived now. 

We wont be making a version compatible with a php version lower than 8 because we don't have any interest in doing so and we don't need it ourselves anyway.

**Comment by chiiya** [comment]
Thanks, that works for me.
